// Novus Ordo: the capstone of the Great Seal, from the back of the dollar bill, for projecting over a
// real pyramid (so no pyramid body: the real one is underneath). The eye in its triangle, the glory of
// rays and light around it, "ANNUIT COEPTIS" arched over the top and "NOVUS ORDO SECLORUM" on the
// scroll below, engraved in the bill's greens: dark ink on pale paper with guilloche lines, or (Paper
// off) glowing green on black. The rays and glow pulse with the kick, swell into the drop and burst on
// it; the eye looks round, blinks on the last beat of some bars and opens wide on the drop; a light runs
// along the lettering every bar.
// Params are p_* uniforms; ranges and defaults are in illuminati.json.
// @messages: ANNUIT    COEPTIS|NOVUS ORDO SECLORUM|MDCCLXXVI
// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_C 2.0
#define CH_D 3.0
#define CH_E 4.0
#define CH_I 5.0
#define CH_L 6.0
#define CH_M 7.0
#define CH_N 8.0
#define CH_O 9.0
#define CH_P 10.0
#define CH_R 11.0
#define CH_S 12.0
#define CH_T 13.0
#define CH_U 14.0
#define CH_V 15.0
#define CH_X 16.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(34350.0, 14881.0);   // C
  if (c < 3.5) return vec2(575023.0, 15921.0);   // D
  if (c < 4.5) return vec2(492607.0, 31777.0);   // E
  if (c < 5.5) return vec2(135310.0, 14468.0);   // I
  if (c < 6.5) return vec2(33825.0, 31777.0);   // L
  if (c < 7.5) return vec2(710513.0, 17969.0);   // M
  if (c < 8.5) return vec2(708145.0, 17977.0);   // N
  if (c < 9.5) return vec2(575022.0, 14897.0);   // O
  if (c < 10.5) return vec2(509487.0, 1057.0);   // P
  if (c < 11.5) return vec2(509487.0, 17701.0);   // R
  if (c < 12.5) return vec2(459838.0, 15888.0);   // S
  if (c < 13.5) return vec2(135327.0, 4228.0);   // T
  if (c < 14.5) return vec2(575025.0, 14897.0);   // U
  if (c < 15.5) return vec2(575025.0, 4433.0);   // V
  if (c < 16.5) return vec2(141873.0, 17962.0);   // X
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 33281.0; if (k < 1.5) return 53582.0; if (k < 2.5) return 0.0; if (k < 3.5) return 36992.0; if (k < 4.5) return 53892.0; if (k < 5.5) return 773.0; return 0.0; }   // ANNUIT    COEPTIS
  if (m < 1.5) { if (k < 0.5) return 62024.0; if (k < 1.5) return 782.0; if (k < 2.5) return 13001.0; if (k < 3.5) return 49161.0; if (k < 4.5) return 24708.0; if (k < 5.5) return 58057.0; if (k < 6.5) return 7.0; return 0.0; }   // NOVUS ORDO SECLORUM
  if (m < 2.5) { if (k < 0.5) return 8391.0; if (k < 1.5) return 65922.0; if (k < 2.5) return 21456.0; return 0.0; }   // MDCCLXXVI
  return 0.0;
}
float msgCount() { return 3.0; }
float msgLen(float m) {
  if (m < 0.5) return 17.0;
  if (m < 1.5) return 19.0;
  if (m < 2.5) return 9.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 2.0;
  if (abs(c - 3.0) < 0.5) return 3.0;
  if (abs(c - 4.0) < 0.5) return 4.0;
  if (abs(c - 5.0) < 0.5) return 8.0;
  if (abs(c - 6.0) < 0.5) return 11.0;
  if (abs(c - 7.0) < 0.5) return 12.0;
  if (abs(c - 8.0) < 0.5) return 13.0;
  if (abs(c - 9.0) < 0.5) return 14.0;
  if (abs(c - 10.0) < 0.5) return 15.0;
  if (abs(c - 11.0) < 0.5) return 17.0;
  if (abs(c - 12.0) < 0.5) return 18.0;
  if (abs(c - 13.0) < 0.5) return 19.0;
  if (abs(c - 14.0) < 0.5) return 20.0;
  if (abs(c - 15.0) < 0.5) return 21.0;
  if (abs(c - 16.0) < 0.5) return 23.0;
  return -1.0;
}
// </text>
uniform float p_size, p_cy, p_tri, p_open, p_look, p_blink, p_rays, p_raylen, p_rspin, p_glow, p_beat, p_drop,
              p_text, p_tsize, p_sweep, p_scroll, p_ring, p_guil, p_hatch, p_paper, p_follow, p_date;

#define TAU 6.2831853
#define PI 3.1415927

// Equilateral triangle, apex up (y up), half side r, centred on its centroid (after Inigo Quilez).
float sdTri(vec2 p, float r) {
  const float k = 1.7320508;
  p.x = abs(p.x) - r;
  p.y = p.y + r / k;
  if (p.x + k * p.y > 0.0) p = vec2(p.x - k * p.y, -k * p.x - p.y) / 2.0;
  p.x -= clamp(p.x, -2.0 * r, 0.0);
  return -length(p) * sign(p.y);
}

float stroke(float d, float w, float px) { return 1.0 - smoothstep(w - px, w + px, abs(d)); }

// Lettering on an arc round c, standing on it. top: arched over c (letter tops outward); otherwise the
// smile underneath (tops towards c). h: letter height. Spacing follows the letter height, so the arc's
// span comes out of the message length. x: coverage, y: how far along the line (0..1).
vec2 arcText(vec2 p, vec2 c, float R, float h, float m, bool top, float px) {
  vec2 d = p - c;
  float r = length(d);
  float W = 6.0 * msgLen(m) - 1.0;
  float span = W * (h / 7.0) * 1.12 / R;
  float a = top ? atan(d.x, d.y) : atan(d.x, -d.y);
  float along = a / span + 0.5;
  float fy = top ? (R + 0.5 * h - r) / h * 7.0 : (r - (R - 0.5 * h)) / h * 7.0;
  if (along < -0.02 || along > 1.02 || fy < -0.5 || fy > 7.5) return vec2(0.0, along);
  return vec2(textCov(vec2(along * W, fy), m, px / (h / 7.0)), along);
}

vec3 content(vec2 uv) {
  float t = u_beat;
  float k = kick() * p_beat;
  bool isDrop = abs(u_scene - 7.0) < 0.5;
  float burst = isDrop ? exp(-0.3 * u_since) * p_drop : 0.0;                   // the drop's flash, fading over bars
  float build = max(dropArc(), (abs(u_scene - 4.0) < 0.5 || abs(u_scene - 6.0) < 0.5) ? u_sp : 0.0);
  vec2 p = (uv - 0.5) * vec2(u_aspect, 1.0) / p_size;
  p.y = -p.y;                                                                  // y up
  float px = u_px / p_size;

  // The bill's greens. Paper on: dark ink on pale paper. Off: the ink glows on black.
  vec3 paper = vec3(0.84, 0.87, 0.76), ink = vec3(0.09, 0.19, 0.13), mid = vec3(0.33, 0.48, 0.36);
  vec3 lit = vec3(0.62, 0.92, 0.66);
  if (p_follow > 0.5) { ink = hsv(u_hue, 0.65, 0.2); mid = hsv(u_hue, 0.45, 0.48); lit = hsv(u_hue, 0.35, 0.95); paper = hsv(u_hue, 0.1, 0.86); }
  vec3 bg = mix(vec3(0.0), paper, p_paper);
  vec3 inkC = mix(lit, ink, p_paper);                                          // lines: dark on paper, light on black
  vec3 midC = mix(lit * 0.55, mid, p_paper);

  vec2 c = vec2(0.0, p_cy);                                                    // the eye's centre
  vec2 q = p - c;
  float r = length(q), ang = atan(q.y, q.x);
  float tri = p_tri;

  // ---- paper: guilloche, rosette lines round the seal, turning slowly
  vec3 col = bg;
  if (p_guil > 0.0) {
    float g1 = sin(r * 150.0 + 2.5 * sin(ang * 12.0 + t * 0.04));
    float g2 = sin(r * 150.0 - 2.5 * sin(ang * 12.0 - t * 0.04));
    float gl = max(stroke(g1, 0.18, px * 150.0), stroke(g2, 0.18, px * 150.0)) * smoothstep(1.2, 0.2, r);
    col = mix(col, midC, gl * p_guil * 0.45);
  }

  // ---- the glory: rays from the eye, long and short in turn, and the light round the capstone
  float n = floor(p_rays + 0.5);
  float rot = t * p_rspin * 0.04;
  float sector = (ang / TAU + 0.5 + rot) * n;
  float idx = floor(sector), f = fract(sector);
  float start = tri * 0.62;
  float len = p_raylen * (1.0 + 0.3 * k + 0.6 * build + 0.9 * burst) * (mod(idx, 2.0) < 0.5 ? 1.0 : 0.62);
  float across = abs(f - 0.5) * TAU / n * r;                                   // distance from the ray's centre line
  float wRay = mix(0.006, 0.0015, clamp((r - start) / max(len, 0.01), 0.0, 1.0));
  float ray = (1.0 - smoothstep(wRay - px, wRay + px, across))
            * smoothstep(start, start + 0.03, r) * (1.0 - smoothstep(start + len * 0.6, start + len, r));
  float glow = exp(-max(r - tri * 0.4, 0.0) * 5.0) * p_glow * (0.55 + 0.35 * k + 0.7 * build + burst);
  col = mix(col, inkC, ray * (0.55 + 0.45 * k) * (n > 0.5 ? 1.0 : 0.0));
  col += lit * glow * mix(0.9, 0.45, p_paper);

  // ---- the capstone: engraved hatching, darker towards the edges, lit up on the drop
  float dt = sdTri(q, tri);
  float inside = 1.0 - smoothstep(-px, px, dt);
  if (inside > 0.0) {
    float shade = smoothstep(-tri * 0.5, 0.0, dt);                             // 0 deep inside .. 1 at the edge
    float period = tri * 0.055;
    float hl = abs(fract(q.y / period) - 0.5) * period;
    float hatch = stroke(hl, period * (0.12 + 0.3 * shade), px) * p_hatch;
    vec3 fill = mix(mix(vec3(0.02, 0.06, 0.04), paper * 0.97, p_paper), lit, 0.25 * build + 0.6 * burst);
    fill = mix(fill, midC, hatch);
    col = mix(col, fill, inside);
  }
  col = mix(col, inkC, stroke(dt, 0.005, px));

  // ---- the eye: almond lids, iris with fibres, pupil, a highlight
  float o = p_open;
  o = mix(o, 1.0, build * 0.6);
  if (isDrop) o = mix(o, 1.0, smoothstep(0.0, 1.0, u_since));
  float bb = mod(t, 4.0);
  if (hash(vec2(floor(t / 4.0), 7.1)) < p_blink && bb > 3.0) o *= 1.0 - sin(PI * clamp((bb - 3.0) / 0.5, 0.0, 1.0));
  vec2 e = q - vec2(0.0, -tri * 0.1);
  float EW = tri * 0.66;                                                       // half width of the almond
  float xn = e.x / EW;
  float hh = o * EW * 0.42 * max(0.0, 1.0 - xn * xn);
  float sl = o * EW * 0.42 * 2.0 * e.x / (EW * EW);
  float de = abs(e.x) > EW ? length(vec2(abs(e.x) - EW, e.y)) : (abs(e.y) - hh) / sqrt(1.0 + sl * sl);
  float eyeIn = 1.0 - smoothstep(-px, px, de);
  vec2 look = p_look * vec2(0.3 * EW * sin(t * TAU / 16.0 + 1.3 * sin(t * 0.11)), 0.08 * EW * sin(t * TAU / 10.0 + 0.7));
  vec2 iq = e - look;
  float ir = length(iq), ia = atan(iq.y, iq.x);
  float ri = EW * 0.42;
  float rp = ri * clamp(0.42 * (1.0 + 0.5 * (u_energy - 0.5)) * (1.0 + 0.25 * k) * (1.0 + 0.3 * burst), 0.1, 0.9);
  float fib = 0.5 + 0.5 * cos(ia * 28.0 + 2.0 * sin(ir * 60.0));
  vec3 sclera = mix(vec3(0.08, 0.14, 0.1), paper * 1.03, p_paper);
  vec3 eyeC = sclera;
  float irisM = 1.0 - smoothstep(ri - px, ri + px, ir);
  eyeC = mix(eyeC, mix(midC, inkC, 0.35 + 0.4 * fib), irisM);
  eyeC = mix(eyeC, inkC, stroke(ir - ri, 0.003, px));
  eyeC = mix(eyeC, mix(ink, vec3(0.0), 1.0 - p_paper) * (1.0 - 0.3 * burst) + lit * burst * 0.4, 1.0 - smoothstep(rp - px, rp + px, ir));
  eyeC = mix(eyeC, mix(vec3(1.0), paper * 1.1, 0.3), 1.0 - smoothstep(ri * 0.16 - px, ri * 0.16 + px, length(iq - vec2(-0.35, 0.35) * ri)));
  col = mix(col, eyeC, eyeIn);
  col = mix(col, inkC, stroke(de, 0.0045, px) * step(0.02, o));
  // the brow line over the upper lid
  float brow = e.y - (EW * 0.42 * 1.2 * max(0.0, 1.0 - xn * xn) + EW * 0.1);
  col = mix(col, inkC, stroke(brow, 0.003, px) * step(abs(xn), 0.85) * 0.8);

  // ---- lettering: arched motto over the top, the scroll underneath; a light runs along it every bar
  if (p_text > 0.5) {
    float h = p_tsize;
    float sw = fract(t / 4.0);
    vec2 a1 = arcText(p, c, tri * 1.8, h, 0.0, true, px);
    float s1 = p_sweep * exp(-pow((a1.y - sw) * 7.0, 2.0)) * (0.5 + 0.5 * k);
    col = mix(col, mix(inkC, lit, s1), a1.x);
    col += lit * a1.x * s1 * 0.5;

    vec2 sc = c + vec2(0.0, 0.62);
    float R2 = 0.62 + tri * 1.42, h2 = h * 0.82;
    if (p_scroll > 0.5) {                                                      // the scroll: a curved ribbon
      float d2 = length(p - sc) - R2;
      float a2 = atan(p.x - sc.x, -(p.y - sc.y));
      float halfSpan = (6.0 * msgLen(1.0) - 1.0) * (h2 / 7.0) * 1.12 / R2 * 0.5 + 0.06;
      float band = 1.0 - smoothstep(h2 * 0.95 - px, h2 * 0.95 + px, abs(d2));
      float inSpan = 1.0 - smoothstep(halfSpan - 0.004, halfSpan, abs(a2));
      float rib = band * inSpan;
      col = mix(col, mix(vec3(0.03, 0.08, 0.05), paper * 1.04, p_paper), rib);
      col = mix(col, inkC, (stroke(abs(d2) - h2 * 0.95, 0.003, px) * inSpan + stroke((abs(a2) - halfSpan) * R2, 0.003, px) * band));
    }
    vec2 a2t = arcText(p, sc, R2, h2, 1.0, false, px);
    float s2 = p_sweep * exp(-pow((a2t.y - fract(sw + 0.5)) * 7.0, 2.0)) * (0.5 + 0.5 * k);
    col = mix(col, mix(inkC, lit, s2), a2t.x);
    col += lit * a2t.x * s2 * 0.5;

    if (p_date > 0.5) {                                                        // MDCCLXXVI under the capstone
      float hd = h * 0.6;
      vec2 dq = (q - vec2(-(6.0 * msgLen(2.0) - 1.0) * hd / 7.0 * 0.5, -tri * 0.58 - hd * 0.6)) / (hd / 7.0);
      col = mix(col, inkC, textCov(vec2(dq.x, 7.0 - dq.y), 2.0, px / (hd / 7.0)));
    }
  }

  // ---- the seal's ring
  if (p_ring > 0.5) {
    float rr = tri * 2.3;
    col = mix(col, inkC, max(stroke(r - rr, 0.004, px), stroke(r - rr - 0.018, 0.0018, px)));
  }

  // The drop's flash over everything, and a little light on every kick.
  col += lit * burst * 0.25 * smoothstep(0.9, 0.0, r);
  return col;
}
